### ISSUE TITLE
testDPC app crashing on Android 13

### ISSUE THREAD

**Issue by aspiqconnect** [googlesamples/android-testdpc#184]
Hello,

I am using testDPC for testing purposes, unfortunately I am no longer able to open the UI the app isn't working properly (keeps crashing) We have set device owner admin for testDPC and disallowed delete the app and also factory reset.

Is there anything else you could help with?

I am sending the Logcat logs in another email.

Thank you for your support.

Best 

2023-08-31 14:18:19.152  8654-8654  samples.testdpc         pid-8654                             E  Not starting debugger since process cannot load the jdwp agent.
2023-08-31 14:18:19.159  8654-8654  Compatibil...geReporter pid-8654                             D  Compat change id reported: 171979766; UID 10244; state: DISABLED
2023-08-31 14:18:19.162  3303-4127  AssistantForeground     pid-3303                             I  (REDACTED) Get launcher package: %s
2023-08-31 14:18:19.167  8654-8654  nativeloader            pid-8654                             D  Configuring classloader-namespace for other apk /data/app/~~ur20rn1Vl5WMkKyXUEHWSA==/com.afwsamples.testdpc-xo1IDWQOSH3jNG7uBC56fw==/base.apk. target_sdk_version=30, uses_libraries=, library_path=/data/app/~~ur20rn1Vl5WMkKyXUEHWSA==/com.afwsamples.testdpc-xo1IDWQOSH3jNG7uBC56fw==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.afwsamples.testdpc
2023-08-31 14:18:19.172  8654-8654  GraphicsEnvironment     pid-8654                             V  ANGLE Developer option for 'com.afwsamples.testdpc' set to: 'default'
2023-08-31 14:18:19.172  8654-8654  GraphicsEnvironment     pid-8654                             V  ANGLE GameManagerService for com.afwsamples.testdpc: false
2023-08-31 14:18:19.172  8654-8654  GraphicsEnvironment     pid-8654                             V  Neither updatable production driver nor prerelease driver is supported.
2023-08-31 14:18:19.172  8654-8654  NetworkSecurityConfig   pid-8654                             D  No Network Security Config specified, using platform default
2023-08-31 14:18:19.172  8654-8654  NetworkSecurityConfig   pid-8654                             D  No Network Security Config specified, using platform default
2023-08-31 14:18:19.190  8654-8654  DevicePoli...atewayImpl pid-8654                             D  constructor: admin=null, dpm=android.app.admin.DevicePolicyManager@4f63ad2
2023-08-31 14:18:19.191  8654-8654  Compatibil...geReporter pid-8654                             D  Compat change id reported: 183155436; UID 10244; state: DISABLED
2023-08-31 14:18:19.223  8654-8654  AndroidRuntime          pid-8654                             D  Shutting down VM
2023-08-31 14:18:19.223  8654-8654  AndroidRuntime          pid-8654                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.afwsamples.testdpc, PID: 8654
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afwsamples.testdpc/com.afwsamples.testdpc.PolicyManagementActivity}: java.lang.SecurityException: Calling identity is not authorized
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.SecurityException: Calling identity is not authorized
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2995)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2920)
                                                                                                    	at android.app.admin.IDevicePolicyManager$Stub$Proxy.isSecurityLoggingEnabled(IDevicePolicyManager.java:10672)
                                                                                                    	at android.app.admin.DevicePolicyManager.isSecurityLoggingEnabled(DevicePolicyManager.java:12619)
                                                                                                    	at com.afwsamples.testdpc.policy.PolicyManagementFragment.isSecurityLoggingEnabled(PolicyManagementFragment.java:1763)
                                                                                                    	at com.afwsamples.testdpc.policy.PolicyManagementFragment.lambda$onCreatePreferences$98$PolicyManagementFragment(PolicyManagementFragment.java:668)
                                                                                                    	at com.afwsamples.testdpc.policy.PolicyManagementFragment$$Lambda$12.validateConstraint(Unknown Source:2)
                                                                                                    	at com.afwsamples.testdpc.common.preference.DpcPreferenceHelper.findConstraintViolation(DpcPreferenceHelper.java:244)
                                                                                                    	at com.afwsamples.testdpc.common.preference.DpcPreferenceHelper.disableIfConstraintsNotMet(DpcPreferenceHelper.java:220)
                                                                                                    	at com.afwsamples.testdpc.common.preference.DpcPreferenceHelper.addCustomConstraint(DpcPreferenceHelper.java:206)
                                                                                                    	at com.afwsamples.testdpc.common.preference.DpcPreferenceHelper.setCustomConstraint(DpcPreferenceHelper.java:192)
                                                                                                    	at com.afwsamples.testdpc.common.preference.DpcPreference.setCustomConstraint(DpcPreference.java:103)
                                                                                                    	at com.afwsamples.testdpc.policy.PolicyManagementFragment.onCreatePreferences(PolicyManagementFragment.java:671)
                                                                                                    	at androidx.preference.PreferenceFragment.onCreate(PreferenceFragment.java:225)
                                                                                                    	at com.afwsamples.testdpc.common.BaseSearchablePolicyPreferenceFragment.onCreate(BaseSearchablePolicyPreferenceFragment.java:53)
                                                                                                    	at com.afwsamples.testdpc.policy.PolicyManagementFragment.onCreate(PolicyManagementFragment.java:558)
                                                                                                    	at android.app.Fragment.performCreate(Fragment.java:2486)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
                                                                                                    	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
                                                                                                    	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
                                                                                                    	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
                                                                                                    	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
                                                                                                    	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8350)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
2023-08-31 14:18:19.223  8654-8654  AndroidRuntime          pid-8654                             E  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
                                                                                                    	... 12 more
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.internal.util.Preconditions.checkCallAuthorization(Preconditions.java:247)
                                                                                                    	at com.android.server.devicepolicy.DevicePolicyManagerService.isSecurityLoggingEnabled(DevicePolicyManagerService.java:15005)
                                                                                                    	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:5110)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1280)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1244)
2023-08-31 14:18:19.224  1457-2044  ActivityTaskManager     pid-1457                             W    Force finishing activity com.afwsamples.testdpc/.PolicyManagementActivity
2023-08-31 14:18:19.233  8654-8654  Process                 pid-8654                             I  Sending signal. PID: 8654 SIG: 9

**Comment by pfmaggi** [comment]
We have a new release that should fix this, can you please test it again?

**Comment by aspiqconnect** [comment]
Hello,

I upgraded testDPC to 9.0.1 and problem still persists. 
Also tried to upgrade to Android 14 and testDPC 9.0.1 and problem still persists. 

Unfortunately, i am unable to delete testDPC unless i factory reset my device. Any suggestions?

**Comment by pfmaggi** [comment]
We're going to take a look.

> Unfortunately, i am unable to delete testDPC unless i factory reset my device. Any suggestions?

How is it set up the device? Have you installed TestDPC as Device or Profile Owner?
